name: pharmabuddy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_nav_bar: ^5.0.6
  flutter_local_notifications: ^16.2.0
  timezone: 
  provider: ^6.0.1
  http: ^0.13.3
  permission_handler: ^11.0.1
  google_maps_flutter: ^2.5.0
  location: ^5.0.0
  flutter_plugin_android_lifecycle:
  geocoding: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
